apiVersion: charts.vizualplatform.com/v1alpha1
kind: Helm1
metadata:
  name: helm1-sample
spec:
  # Default values copied from <project_dir>/helm-charts/helm1/values.yaml
  affinity: {}
  autoscaling:
    enabled: false
    maxReplicas: 100
    minReplicas: 1
    targetCPUUtilizationPercentage: 80
  fullnameOverride: ""
  image:
    pullPolicy: Always
    repository: nginx
    tag: image1
  imagePullSecrets: []
  ingress:
    annotations: {}
    enabled: false
    hosts:
    - host: chart-example.local
      paths: []
    tls: []
  nameOverride: ""
  nodeSelector: {}
  podAnnotations: {}
  podSecurityContext: {}
  replicaCount: 1
  resources: {}
  securityContext: {}
  service:
    port: 80
    type: NodePort
  serviceAccount:
    annotations: {}
    create: true
    name: helm1svc
  tolerations: []
  
  
