---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: bpmn-mongodb
spec:
  members: 1   ### Make sure you create a 2 node cluster.
  type: ReplicaSet
  version: "4.2.6"
  security:
    authentication:
      modes: ["SCRAM"]
    roles: # custom roles are defined here
      - role: bpnmRole
        db: admin
        privileges:
          - resource:
              db: "bpmn"
              collection: "Cbpmn" # an empty string indicates any collection
            actions:
              - find
              - listDatabases
              - dropCollection
              - createCollection
              - createIndex
              - dropIndex
        roles: []
  users:
    - name: my-user
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: my-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: bpnmRole # apply the custom role to the user
          db: admin
      scramCredentialsSecretName: my-scram
    # - name: bpmn
    #   db: bpmn
    #   passwordSecretRef: # a reference to the secret that will be used to generate the user's password
    #     name: db-user-password
    #   roles:
    #     - name: bpnmRole # apply the custom role to the user
    #       db: bpmn
    #   scramCredentialsSecretName: my-scram
  statefulSet:
    spec:
      template:
        spec:
          # resources can be specified by applying an override
          # per container name.
          containers:
            - name: mongod
              resources:
                limits:
                  cpu: "0.2"
                  memory: 250M
                requests:
                  cpu: "0.2"
                  memory: 200M
            - name: mongodb-agent
              resources:
                limits:
                  cpu: "0.2"
                  memory: 250M
                requests:
                  cpu: "0.2"
                  memory: 200M
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib

# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: my-user-password
type: Opaque
stringData:
  password: password

---
apiVersion: v1
kind: Secret
metadata:
  name: db-user-password
type: Opaque
stringData:
  password: password