apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # server: https://acme-v02.api.letsencrypt.org/directory
    email: ranjithkumar.359@gmail.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
       ingress:
         class: dev-nginx
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: le-crt
spec:
  secretName: tls-secret
  issuerRef:
    kind: Issuer
    name: letsencrypt
  commonName: st1-dev-vnext.example.com
  dnsNames:
  - st1-dev-vnext.example.com
