apiVersion: charts.vizualplatform.com/v1alpha1
kind: Vizualplatform
metadata:
  name: vizualplatform-sample
spec:
  # Default values copied from <project_dir>/helm-charts/vizualplatform/values.yaml
  affinity: {}
  autoscaling:
    enabled: false
    maxReplicas: 100
    minReplicas: 1
    targetCPUUtilizationPercentage: 80
  fullnameOverride: vizualplatform-chart
  image:
    pullPolicy: Always
    repository: nginx
    tag: ""
  imagePullSecrets: []
  ingress:
    annotations: {}
    enabled: false
    hosts:
    - host: chart-example.local
      paths: []
    tls: []
  nameOverride: vizualplatform-app
  nodeSelector: {}
  podAnnotations: {}
  podSecurityContext: {}
  replicaCount: 1
  resources: {}
  securityContext: {}
  service:
    port: 80
    type: NodePort
  serviceAccount:
    annotations: {}
    create: true
    name: vizualplatform
  tolerations: []
  
  
