apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dev.fullname" . }}
  labels:
    {{- include "dev.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "dev.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- if eq .Chart.AppVersion "latest" }}
        rollme: {{ randAlphaNum 5 | quote }}
        {{- end }}
      {{- include "dev.podAnnotations" . | nindent 8 }}
      labels:
        {{- include "dev.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dev.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- range $name, $value := .Values.env.devEnv }}
              {{- if not (empty $value) }}
            - name: {{ $name | quote }}
              value: {{ $value | quote }}
              {{- end }}
          {{- end }}
          {{- range $key, $secrets := .Values.secrets }}
            - name: {{ $key | quote }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secrets.secretKeyRef | quote }}
                  key: {{ $secrets.key | quote }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
{{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path | default "/" }}
              port: {{ .Values.service.port | default 80 }}
            failureThreshold: {{ .Values.livenessProbe.periodSeconds | default 1 }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds | default 180 }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds | default 20 }}
            successThreshold: {{ .Values.livenessProbe.successThreshold | default 1 }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds | default 5 }}
{{- end }}
{{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path | default "/" }}
              port: {{ .Values.service.port | default 80 }}
            failureThreshold: {{ .Values.readinessProbe.periodSeconds | default 1 }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds | default 60 }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds | default 20 }}
            successThreshold: {{ .Values.readinessProbe.successThreshold | default 1 }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds | default 5 }}
{{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
