ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "dev-nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  path: /kibana(/|$)(.*)
  hosts:
    - kibana.example.com
extraEnvs:
  - name: SERVER_BASEPATH
    value: "/kibana"

healthCheckPath: /api/status

fullnameOverride: "kibana"

resources:
  requests:
    cpu: "100m"
  limits:
    cpu: "1000m"
