# permissions for end users to view helm3s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helm3-viewer-role
rules:
- apiGroups:
  - charts.vizualplatform.com
  resources:
  - helm3s
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - charts.vizualplatform.com
  resources:
  - helm3s/status
  verbs:
  - get
